// use CommonJS instead of ES modules

//What this does: This script fetches assignments for a specific section (identified by SECTION_ID) from the Sky API using provided subscription key and access token for authentication.
//Also, the json file is just auto-generated by npm to lock dependencies and their versions
//Another also, package.json defines the project’s metadata and dependencies for Node.js and tells npm the project name, version, main file, scripts, license, module type, and which packages are required.

const fetch = (...args) => import('node-fetch').then(({ default: fetch }) => fetch(...args));

// --- Replace these values ---
const SUBSCRIPTION_KEY = ""; // Your Sky API subscription key
const ACCESS_TOKEN = "";   // You’ll get this via OAuth later
//Current Refresh_Token: ""
const SECTION_ID = 12345;                   // Replace with a real section ID if available

const url = `https://api.sky.blackbaud.com/school/v1/academics/sections/${SECTION_ID}/assignments`;

const headers = {
  "Bb-Api-Subscription-Key": SUBSCRIPTION_KEY,  // <-- header name stays constant
  "Authorization": `Bearer ${ACCESS_TOKEN}`,    // <-- header name is Authorization
  "Cache-Control": "no-cache"
};

async function getAssignments() {
  try {
    const response = await fetch(url, { headers });
    console.log("Status:", response.status);
    
    const data = await response.json();
    console.log(JSON.stringify(data, null, 2));
  } catch (error) {
    console.error("Error:", error);
  }
}

getAssignments();